import type { GlossaryEntry } from './glossary';

/** Economía dinámica, jurisdicciones, profesionales, grupos y sistema legal (Fase 4). */
export const GLOSSARY_WORLD: GlossaryEntry[] = [
  // ------------------------------------------------------------ Economía
  { id: 'ciclo_economico', term: 'Ciclo económico', category: 'Economía',
    short: 'La economía alterna fases de expansión, auge, desaceleración, recesión y recuperación.',
    purpose: 'Anticipar cómo cambian el empleo, las ventas, los precios de los activos y el crédito.',
    how: 'Cada fase dura entre un mínimo y un máximo de meses; pasado el mínimo, cada mes aumenta la probabilidad de cambiar. En la fase actual tienden el PIB, el desempleo y la confianza hacia sus valores típicos, con inercia y ruido.',
    example: 'Recesión: PIB −2 %, desempleo 8.5 %, confianza 0.84 → menos ventas, más impagos de inquilinos, bolsa en baja, bancos más exigentes.',
    impact: 'Afecta a todos tus sistemas a la vez: carrera, empresas, inversiones, inmuebles y crédito.',
    tip: 'Tener liquidez al entrar en una recesión permite comprar activos baratos.',
  },
  { id: 'recesion', term: 'Recesión', category: 'Economía',
    short: 'Período en que la producción cae y el desempleo sube.',
    purpose: 'Es la fase de mayor riesgo para deudores y empresas cíclicas.',
    example: 'En recesión aumentan los despidos, las ventas de muebles y cafeterías caen más que las de minimercados, y los precios inmobiliarios bajan.',
    impact: 'Más riesgo de perder el empleo (sobre todo con bajo desempeño), crédito más caro y exigente.',
    risks: 'Deudas altas + ingresos que caen = insolvencia.',
  },
  { id: 'pib', term: 'Crecimiento del PIB', category: 'Economía',
    short: 'Cuánto crece la producción total de la economía en un año.',
    purpose: 'Es el termómetro general de la economía.',
    example: 'PIB +4.5 % en un auge; −2 % en una recesión.',
    impact: 'Influye en los resultados de las empresas cotizadas, la inflación y la tasa de interés.',
  },
  { id: 'desempleo', term: 'Tasa de desempleo', category: 'Economía',
    short: 'Porcentaje de personas que buscan trabajo y no lo encuentran.',
    purpose: 'Mide cuánto cuesta conseguir empleo.',
    how: 'Con desempleo alto baja la probabilidad de recibir ofertas (hasta −40 %), aumenta el riesgo de recortes y los inquilinos pagan con menos regularidad.',
    formula: 'Factor de empleo = 1 − (desempleo − 5 %) × 4 (entre 0.6 y 1.2)',
    example: 'Con 8 % de desempleo, tu probabilidad de oferta se multiplica por 0.88.',
    impact: 'Carrera, alquileres y demanda de las empresas.',
  },
  { id: 'confianza_consumidor', term: 'Confianza del consumidor', category: 'Economía',
    short: 'Qué tan dispuestos están los hogares a gastar.',
    purpose: 'Determina la demanda de tus empresas.',
    formula: 'Demanda del sector × confianza^(sensibilidad del sector)',
    example: 'Confianza 0.85 en recesión: una mueblería (sensibilidad 1.7) pierde ~24 % de demanda; un minimercado (0.4) solo ~6 %.',
    impact: 'Afecta las ventas de todas tus empresas.',
  },
  { id: 'costo_proveedores', term: 'Índice de costos de proveedores', category: 'Economía',
    short: 'Cuánto más caros (o baratos) están los insumos respecto de lo normal.',
    purpose: 'Explica por qué suben tus costos sin que cambie tu negocio.',
    example: 'Un shock petrolero lleva el índice a 1.12: tus insumos cuestan 12 % más y la inflación sube.',
    impact: 'Se aplica a cada compra de inventario.',
  },
  { id: 'evento_economico', term: 'Eventos económicos', category: 'Economía',
    short: 'Sucesos temporales que alteran la economía: shocks petroleros, crisis bancarias, auges tecnológicos, correcciones inmobiliarias…',
    purpose: 'Introducir sorpresas coherentes con el mundo real.',
    how: 'Cada mes hay ~7 % de probabilidad de un evento (según la dificultad). Cada uno tiene duración y efectos concretos sobre sectores, costos, bolsa, inmuebles, desempleo o crédito.',
    example: 'Crisis bancaria (3–9 meses): crédito +2.5 pp, bolsa en fuerte baja, acciones de bancos −40 % anual, demanda −6 %.',
    impact: 'Se muestran en Economía con su duración estimada.',
  },
  { id: 'dificultad', term: 'Dificultad económica', category: 'Economía',
    short: 'Ajusta la volatilidad, la frecuencia de recesiones y eventos, la exigencia de los bancos y los controles de las autoridades.',
    purpose: 'Adaptar el desafío a tu preferencia.',
    example: 'Fácil: volatilidad ×0.7 y bancos 20 puntos más flexibles. Difícil: recesiones ×1.4 y controles ×1.3.',
    impact: 'No cambia la contabilidad ni las reglas: solo la intensidad de la incertidumbre.',
  },
  // ------------------------------------------------------------ Jurisdicciones
  { id: 'jurisdiccion', term: 'Jurisdicción fiscal', category: 'Impuestos',
    short: 'El país (ficticio) cuyas reglas fiscales se te aplican.',
    purpose: 'Cada una tiene impuestos, deducciones, créditos y controles distintos.',
    how: 'Tu residencia define tus impuestos personales. Cada empresa tributa en la jurisdicción donde está registrada, y cada inmueble paga el impuesto inmobiliario de donde está.',
    example: 'Valdoria: equilibrada. Isla Coral: casi sin impuestos pero cara para vivir. Norvalia: impuestos altos con créditos generosos. Meridia: premia invertir a largo plazo.',
    impact: 'Cambia cuánto pagás por salario, alquileres, ganancias de capital, dividendos e inmuebles.',
  },
  { id: 'residencia_fiscal', term: 'Residencia fiscal', category: 'Impuestos',
    short: 'Dónde tributás como persona.',
    purpose: 'Planificación fiscal legal: elegir dónde vivir según tus ingresos.',
    how: 'El trámite se paga al pedirla y rige desde el 1 de enero siguiente. Al mudarte, tus gastos de vida se ajustan al costo de vida del lugar. Isla Coral exige patrimonio mínimo.',
    example: 'Si vivís de ganancias de capital grandes, Isla Coral (0 %) puede convenir aunque vivir allí cueste 40 % más.',
    impact: 'Aplica a la declaración del año siguiente. No podés mudarte con un proceso judicial abierto.',
    versus: 'Planificación fiscal (legal): elegir reglas. Evasión (ilegal): ocultar ingresos.',
  },
  { id: 'ganancia_corto_largo', term: 'Ganancia de capital de corto y largo plazo', category: 'Impuestos',
    short: 'Algunas jurisdicciones cobran menos impuesto si mantuviste la inversión más de un año.',
    purpose: 'Incentivar la inversión de largo plazo.',
    example: 'Meridia: 22 % si vendés antes de un año, 10 % después. Norvalia: 30 % y 15 %.',
    impact: 'El plazo se mide por lote (FIFO) desde la compra.',
  },
  { id: 'arrastre_perdidas', term: 'Arrastre de pérdidas de capital', category: 'Impuestos',
    short: 'Las pérdidas netas de un año compensan ganancias de años siguientes.',
    purpose: 'Que tributes sobre tu ganancia neta a lo largo del tiempo.',
    example: 'Perdiste $4,000 en 2026 y ganaste $6,000 en 2027: tributás solo sobre $2,000.',
    impact: 'El plazo depende de la jurisdicción (5 años en Valdoria, 10 en Norvalia, sin límite en Meridia).',
  },
  { id: 'deduccion_documental', term: 'Deducciones documentales', category: 'Impuestos',
    short: 'Deducciones que exigen registros correctos: depreciación de inmuebles alquilados e intereses hipotecarios.',
    purpose: 'Pagar solo lo que corresponde sobre tus alquileres.',
    how: 'Sin conocimientos contables reclamás una parte (50 % + 0.8 % por nivel de Contabilidad). Un contador contratado reclama 82 %–100 % según su calidad.',
    example: 'Depreciación anual de $3,000: con Contabilidad 10 reclamás $1,740; con un buen contador, casi $3,000.',
    impact: 'Menos impuesto sobre alquileres.',
  },
  { id: 'costo_vida', term: 'Costo de vida', category: 'Impuestos',
    short: 'Cuánto cuesta vivir en una jurisdicción respecto de Valdoria.',
    purpose: 'Considerarlo junto con los impuestos al elegir residencia.',
    example: 'Isla Coral ×1.4: un presupuesto de $1,500 pasa a $2,100.',
    impact: 'Multiplica tus gastos de vida al mudarte.',
  },
  // ------------------------------------------------------------ Profesionales
  { id: 'profesionales', term: 'Profesionales contratables', category: 'Profesionales',
    short: 'Contadores, asesores financieros, abogados, auditores y gerentes que trabajan para vos o tus empresas.',
    purpose: 'Delegar tareas especializadas y reducir riesgos. Contratarlos es opcional.',
    how: 'Cada uno tiene experiencia, especialidad, honorario, reputación pública y una calidad real de servicio que la reputación solo estima (puede engañar). El mercado se renueva cada 60 días.',
    example: 'Un abogado con reputación 80 y 20 años de experiencia cobra más, pero acelera desalojos, detecta vicios ocultos y mejora tu defensa.',
    impact: 'Honorarios mensuales como gasto; efectos concretos en impuestos, inversiones, juicios y empresas.',
  },
  { id: 'contador', term: 'Contador', category: 'Profesionales',
    short: 'Lleva tus registros, prepara informes y revisa obligaciones fiscales.',
    purpose: 'Pagar lo justo y no olvidar vencimientos.',
    how: 'Personal: reclama deducciones documentales, prepara el informe de obligaciones, reduce errores en auditorías y te advierte si tu declaración es irregular. En una empresa: evita errores en la declaración de sociedades y detecta desfalcos.',
    example: 'Una empresa sin contador tiene hasta 12 % de probabilidad de error en su declaración anual (multa).',
    impact: 'Honorario mensual.',
  },
  { id: 'asesor_financiero', term: 'Asesor financiero', category: 'Profesionales',
    short: 'Analiza inversiones, compara riesgos y elabora proyecciones.',
    purpose: 'Mejorar tus decisiones de inversión.',
    how: 'Reduce el error de las estimaciones de valor de las acciones (como si tuvieras más habilidad de Predicción) y prepara proyecciones Monte Carlo de tu cartera con más escenarios.',
    formula: 'Honorario mensual = el mayor entre su anticipo y 1 % anual del valor de tu cartera ÷ 12',
    example: 'Cartera de $120,000: 1 % anual = $100/mes; si su anticipo es $300, pagás $300.',
    impact: 'Nunca garantiza resultados.',
  },
  { id: 'abogado', term: 'Abogado', category: 'Profesionales',
    short: 'Revisa contratos, asesora en disputas y te representa en procesos.',
    purpose: 'Reducir riesgos legales y defenderte.',
    how: 'Inspecciona inmuebles sin costo y negocia rebajas por vicios ocultos, detecta contingencias al comprar empresas, acelera desalojos, impugna multas de inspección y te defiende en casos judiciales (revisa expedientes, prepara la defensa, negocia acuerdos, apela).',
    example: 'Con un abogado de calidad 80, la probabilidad de condena baja varios puntos, pero no desaparece si hay pruebas.',
    impact: 'Anticipo mensual + honorarios por caso.',
  },
  { id: 'auditor', term: 'Auditor', category: 'Profesionales',
    short: 'Revisa los libros de una empresa y emite un informe independiente.',
    purpose: 'Detectar errores e irregularidades y dar confianza a terceros.',
    how: 'Verifica que los libros cuadren, detecta desfalcos de empleados y, si encuentra cifras infladas o ventas no declaradas, está obligado a informarlo. Una auditoría limpia da 12 meses de +10 % al múltiplo de valoración y −0.5 pp en préstamos.',
    example: 'Auditoría de $3,000 que encuentra un desfalco de $8,000 y recupera la mitad.',
    impact: 'Pago único por auditoría.',
  },
  { id: 'gerente_profesional', term: 'Gerente profesional', category: 'Profesionales',
    short: 'Un directivo con experiencia que administra una de tus empresas.',
    purpose: 'Delegar la operación diaria con calidad.',
    how: 'Se incorpora como gerente de la empresa con una habilidad igual a su calidad real (−15 % si no es su especialidad). Permite delegar reposición, precios y personal.',
    example: 'Un gerente de calidad 85 en su especialidad toma mejores decisiones de precio que uno de 45.',
    impact: 'Sueldo mensual pagado por la empresa.',
  },
  { id: 'auditoria_limpia', term: 'Auditoría sin salvedades', category: 'Profesionales',
    short: 'Informe de auditoría que no encontró problemas.',
    purpose: 'Demostrar que los números de la empresa son confiables.',
    example: 'Con una auditoría limpia vigente, una empresa se valora 10 % más y paga menos tasa.',
    impact: 'Vigencia de 12 meses.',
  },
  { id: 'desfalco', term: 'Desfalco', category: 'Profesionales',
    short: 'Un empleado se apropia de dinero de la empresa.',
    purpose: 'Es un riesgo real en empresas sin controles.',
    how: 'En empresas con más de 4 empleados, sin contador ni auditoría reciente, hay un riesgo mensual (mayor con baja moral). El faltante aparece cada mes en gastos administrativos hasta que un contador o auditor lo detecta.',
    example: 'Faltan $300 por mes durante 8 meses: $2,400 perdidos.',
    impact: 'Reduce la caja y el resultado de la empresa.',
  },
  // ------------------------------------------------------------ Grupos
  { id: 'holding', term: 'Sociedad holding', category: 'Grupos empresariales',
    short: 'Una empresa cuyo negocio es ser dueña de otras empresas.',
    purpose: 'Administrar varias empresas como grupo: mover capital, centralizar caja y pagar impuestos una sola vez.',
    how: 'La holding registra cada subsidiaria por el método de participación. Los dividendos entre empresas del grupo son exentos; solo tributa lo que la holding reparte a vos. Podés comprar o fundar empresas a su nombre y transferirle las que ya tenés (SRL o corporaciones).',
    example: 'Tu cafetería gana $30,000. Si repartís directo, pagás 10 % de dividendos. Si gira a la holding, no paga; la holding puede reinvertirlo en otra empresa sin impuesto intermedio.',
    impact: 'En tu balance aparece solo la holding: sin contar dos veces sus activos.',
  },
  { id: 'subsidiaria', term: 'Subsidiaria', category: 'Grupos empresariales',
    short: 'Una empresa controlada por otra (su matriz).',
    purpose: 'Separar riesgos entre negocios del mismo dueño.',
    how: 'La matriz la registra en "Inversiones en subsidiarias" (su parte del patrimonio + plusvalía). El resultado de la subsidiaria llega a la matriz como "Resultado de subsidiarias", exento de impuesto porque ya tributó en la subsidiaria.',
    example: 'Si la subsidiaria quiebra, la matriz pierde su inversión, pero el resto del grupo sigue (responsabilidad limitada).',
    impact: 'Riesgo individual separado; riesgo consolidado visible en el informe del grupo.',
  },
  { id: 'prestamo_intragrupo', term: 'Préstamo intragrupo', category: 'Grupos empresariales',
    short: 'Un préstamo entre dos empresas del mismo grupo.',
    purpose: 'Mover caja a donde hace falta sin pedir al banco.',
    how: 'Queda como cuenta por cobrar en la prestamista y por pagar en la deudora; los intereses son ingreso de una y gasto de la otra. En el consolidado se eliminan. Si una empresa sale del grupo, el préstamo se cancela (y lo impago se da de baja).',
    example: 'La holding presta $20,000 al 4 % a la cafetería para una remodelación.',
    impact: 'Riesgo de contagio: si la deudora quiebra, la prestamista pierde.',
  },
  { id: 'consolidacion', term: 'Estados consolidados', category: 'Grupos empresariales',
    short: 'Los estados financieros del grupo como si fuera una sola empresa.',
    purpose: 'Ver el tamaño y el riesgo real del grupo sin contar dos veces.',
    formula: 'Suma de los libros − inversión en subsidiarias − préstamos y resultados intragrupo; la parte de otros socios es interés minoritario',
    example: 'Holding con $10,000 de caja y una subsidiaria al 100 %: el consolidado muestra la caja, inventario y deudas de ambas, pero no la inversión de la holding en la subsidiaria.',
    impact: 'El patrimonio atribuible consolidado coincide con el patrimonio de la holding.',
  },
  { id: 'interes_minoritario', term: 'Interés minoritario', category: 'Grupos empresariales',
    short: 'La parte de una subsidiaria que pertenece a otros socios.',
    purpose: 'Separar lo que es tuyo de lo que es de terceros en el consolidado.',
    example: 'Subsidiaria con patrimonio $100,000 en la que tenés el 80 %: interés minoritario $20,000.',
    impact: 'Se resta para llegar al patrimonio atribuible.',
  },
  { id: 'exencion_participacion', term: 'Exención por participación', category: 'Grupos empresariales',
    short: 'Los dividendos y resultados que una matriz recibe de sus subsidiarias no vuelven a tributar.',
    purpose: 'Evitar la doble imposición dentro de un grupo.',
    example: 'La subsidiaria paga 25 % de impuesto; al girar dividendos a la holding no hay otro impuesto hasta que la holding te reparte a vos.',
    impact: 'Hace conveniente reinvertir dentro del grupo.',
  },
  { id: 'centralizacion_caja', term: 'Centralización de caja (cash pooling)', category: 'Grupos empresariales',
    short: 'Cada mes, la caja excedente de las subsidiarias se presta a la holding.',
    purpose: 'Usar el dinero ocioso del grupo donde rinde más.',
    how: 'Se deja en cada subsidiaria una reserva de 60 días de gastos; el excedente se presta a la matriz (préstamo intragrupo). Si la subsidiaria necesita, la matriz devuelve.',
    example: 'Subsidiaria con $50,000 y reserva de $20,000: $30,000 pasan a la holding.',
    impact: 'Más caja disponible en la holding para invertir.',
  },
  { id: 'honorario_gestion', term: 'Honorario de gestión', category: 'Grupos empresariales',
    short: 'Un porcentaje de las ventas que una subsidiaria paga a su matriz por administrarla.',
    purpose: 'Financiar la holding.',
    example: '2 % de $40,000 de ventas mensuales = $800 a la holding.',
    impact: 'Gasto de la subsidiaria e ingreso de la matriz (se eliminan en el consolidado).',
  },
  // ------------------------------------------------------------ Sistema legal
  { id: 'efectivo_no_declarado', term: 'Efectivo no declarado', category: 'Sistema legal',
    short: 'Dinero de origen no declarado (ficticio) que no pasa por tus cuentas bancarias.',
    purpose: 'Es el resultado de actividades ilegales del juego.',
    how: 'Sirve para pagos no documentados. Depositarlo en el banco genera sospecha; ingresarlo a una empresa como ventas ficticias (lavado) cuesta 10 % y tributa. En una condena se decomisa.',
    example: 'Una operación clandestina te devuelve $12,000 en efectivo no declarado.',
    impact: 'Suma a tu patrimonio, pero no a tu liquidez legal.',
    risks: 'Decomiso total si te condenan.',
  },
  { id: 'soborno', term: 'Soborno (ficticio)', category: 'Sistema legal',
    short: 'Pagar a un funcionario para obtener un favor.',
    purpose: 'En el juego: agilizar permisos, evitar multas de inspección o ganar contratos públicos.',
    how: 'El funcionario puede rechazarlo y denunciarte (entre 10 % y 70 % según la jurisdicción). Si acepta, el acto queda registrado con su prueba y sus testigos y puede descubrirse años después.',
    example: 'Pagar $4,500 para un contrato público de 6 meses que factura $3,500/mes.',
    impact: 'Delito penal: multa, antecedentes, suspensión de la empresa y posible prisión ficticia.',
  },
  { id: 'evasion_fiscal', term: 'Evasión fiscal', category: 'Sistema legal',
    short: 'Ocultar ingresos para pagar menos impuestos. Es ilegal.',
    purpose: 'El juego lo permite como decisión con consecuencias.',
    how: 'Elegís qué porcentaje de ingresos no salariales ocultar (los salarios los informa el empleador). La prueba depende del monto: alquileres, ventas de títulos y cupones dejan rastro bancario. Las auditorías fiscales revisan 5 años.',
    example: 'Ocultar el 50 % de $40,000 de alquileres ahorra ~$4,000 de impuesto… hasta que una auditoría exige el impuesto, intereses y una multa del 50 %–100 %.',
    impact: 'Casos menores: resolución fiscal. Graves: proceso penal.',
    versus: 'La planificación fiscal (elegir jurisdicción, usar deducciones) es legal.',
  },
  { id: 'fraude', term: 'Fraude (ficticio)', category: 'Sistema legal',
    short: 'Engañar a terceros con información falsa para obtener un beneficio.',
    purpose: 'En el juego: inflar los estados de una empresa para obtener más crédito.',
    example: 'Con libros inflados 30 %, el banco ve más EBITDA y presta más. Si se descubre: multa, suspensión y posible prisión.',
    impact: 'Un auditor externo puede detectarlo y debe informarlo.',
  },
  { id: 'negocio_clandestino', term: 'Negocio clandestino (ficticio)', category: 'Sistema legal',
    short: 'Operaciones ilegales abstractas con alto rendimiento y riesgo de allanamiento.',
    purpose: 'Representar economías ilegales dentro del juego, sin detalles reales.',
    example: 'Invertís $10,000 a 60 días con rendimiento esperado 35 % y 12 % de riesgo de allanamiento (perdés todo y se abre un caso).',
    impact: 'El retorno llega como efectivo no declarado.',
  },
  { id: 'lavado', term: 'Lavado de dinero (ficticio)', category: 'Sistema legal',
    short: 'Hacer pasar dinero de origen ilegal como legal.',
    purpose: 'Poder usar el efectivo no declarado en la economía formal.',
    example: 'Registrar $20,000 como ventas en efectivo de tu minimercado: pagás 10 % de comisión y luego impuestos sobre esas "ventas".',
    impact: 'Ventas que crecen de forma llamativa aumentan la prueba.',
  },
  { id: 'sospecha', term: 'Nivel de sospecha', category: 'Sistema legal',
    short: 'Cuánto te vigilan las autoridades (0–100).',
    purpose: 'Resume tu riesgo de ser investigado.',
    how: 'Sube con cada acto ilegal (según gravedad y controles de la jurisdicción), con depósitos grandes y con un patrimonio que crece mucho más que tus ingresos declarados. Baja 4 % por mes.',
    formula: 'Probabilidad mensual de detectar un acto = base × controles × dificultad × (0.5 + sospecha/100) × (1 + testigos × 0.12 × descontento) × (0.5 + prueba/100)',
    example: 'Con sospecha 60 la probabilidad de detección es 2.2 veces mayor que con sospecha 0.',
    impact: 'Aumenta la probabilidad de investigaciones y auditorías.',
  },
  { id: 'testigos', term: 'Testigos y denuncias', category: 'Sistema legal',
    short: 'Personas que saben de un acto ilegal y pueden denunciarlo.',
    purpose: 'Explicar por qué los actos con empleados involucrados son más riesgosos.',
    example: 'Un contador o gerente descontento (moral baja) multiplica la probabilidad de denuncia.',
    impact: 'Cuidar la moral del personal reduce denuncias.',
  },
  { id: 'investigacion', term: 'Investigación', category: 'Sistema legal',
    short: 'La etapa en que la fiscalía reúne pruebas (2–5 meses).',
    purpose: 'Decide si hay imputación o si el caso se archiva.',
    how: 'La fuerza de la acusación crece con la prueba de cada acto. Si al final es menor a 35/100, se archiva. Los casos fiscales menores se resuelven aquí con una resolución administrativa (sin prisión).',
    example: 'Evasión chica detectada: impuesto + intereses + multa del 50 %.',
    impact: 'Estrés y honorarios del abogado.',
  },
  { id: 'imputacion', term: 'Imputación y acuerdo', category: 'Sistema legal',
    short: 'La fiscalía te acusa formalmente y ofrece un acuerdo.',
    purpose: 'Decidir entre un castigo seguro pero reducido y el riesgo de un juicio.',
    how: 'El acuerdo reduce la multa (~30 %) y la prisión (~60 %) a cambio de aceptar la condena. Un abogado puede negociar hasta dos veces para mejorarlo.',
    example: 'Oferta: $18,000 y 4 meses de prisión en suspenso. En juicio podrías ser absuelto… o condenado a $30,000 y 10 meses efectivos.',
    impact: 'Aceptar genera antecedentes.',
  },
  { id: 'juicio', term: 'Juicio', category: 'Sistema legal',
    short: 'Un tribunal decide si sos culpable.',
    purpose: 'Resolver el caso cuando no hay acuerdo.',
    formula: 'P(condena) = 1 ÷ (1 + e^(−(acusación − defensa) ÷ 14)), siempre entre 5 % y 95 %',
    example: 'Acusación 70, defensa 45 (buen abogado + preparación): ~86 %. Con defensor público (defensa ~15): ~98 % → 95 %.',
    impact: 'Absolución: el caso se cierra. Condena: multa, restitución, decomiso, antecedentes y posible prisión.',
    risks: 'Ningún abogado garantiza la absolución.',
  },
  { id: 'apelacion', term: 'Apelación', category: 'Sistema legal',
    short: 'Pedir a un tribunal superior que revise una condena (30 días de plazo).',
    purpose: 'Reducir una sentencia.',
    example: 'Con un buen abogado, ~35 % de probabilidad de reducir a la mitad la multa pendiente y la prisión restante.',
    impact: 'Cuesta dos meses de honorarios del abogado.',
  },
  { id: 'multa', term: 'Multas y sanciones', category: 'Sistema legal',
    short: 'Montos que debés pagar por una infracción o condena.',
    purpose: 'Son la consecuencia económica de un caso.',
    how: 'Se registran como pasivo "Multas por pagar". Podés pagarlas, pedir un plan de 12 cuotas (+10 %) o, si vencen, sufrir embargos.',
    example: 'Multa de $12,000 con 90 días de plazo.',
    impact: 'Reduce tu patrimonio al dictarse.',
  },
  { id: 'embargo', term: 'Embargo', category: 'Sistema legal',
    short: 'Toma forzosa de tu dinero o bienes para pagar una deuda vencida.',
    purpose: 'Cobrar multas impagas.',
    how: 'Cada mes se toma lo disponible en cuenta corriente y ahorro; si no alcanza, se venden tus inversiones (con 3 % de descuento).',
    example: 'Multa vencida de $20,000 con $5,000 en cuentas: se embargan $5,000 y se venden fondos por el resto.',
    impact: 'Además empeora tu puntaje crediticio.',
  },
  { id: 'prision', term: 'Prisión (ficticia)', category: 'Sistema legal',
    short: 'Condena efectiva que te aparta de la vida económica activa durante meses.',
    purpose: 'Ser la consecuencia más grave del sistema.',
    how: 'Perdés el empleo, no podés operar en mercados ni fundar o comprar, tus empresas quedan en manos de sus gerentes (o en piloto automático) y los gastos siguen corriendo. Con 2/3 cumplidos puede haber libertad anticipada. Penas de hasta 12 meses sin antecedentes previos quedan en suspenso.',
    example: 'Condena de 8 meses: durante ese tiempo tus inversiones siguen el mercado y tus empresas operan solas.',
    impact: 'Estrés, salud y reputación. El juego continúa: no hay "game over".',
  },
  { id: 'prescripcion', term: 'Prescripción', category: 'Sistema legal',
    short: 'Pasado cierto tiempo, un acto ya no puede perseguirse.',
    purpose: 'Límite temporal de los riesgos.',
    example: 'Evasión: 6 años desde el año fiscal. Fraude: 8 años.',
    impact: 'El acto deja de sumar riesgo.',
  },
  { id: 'regularizacion', term: 'Regularización voluntaria', category: 'Sistema legal',
    short: 'Declarar y pagar por tu cuenta una evasión antes de que la descubran.',
    purpose: 'Salir del riesgo penal pagando.',
    example: 'Evasión de $3,000 hace un año: pagás ~$3,780 (impuesto + 20 % + intereses) y no hay delito.',
    impact: 'Baja la sospecha 10 puntos.',
  },
  { id: 'defensa_legal', term: 'Defensa legal', category: 'Sistema legal',
    short: 'Tu representación en un proceso judicial.',
    purpose: 'Reducir la probabilidad de condena y el castigo.',
    how: 'Defensa = base del abogado (10 + calidad × 0.35) + preparación × 0.5 + Derecho × 0.1. Revisar el expediente te muestra una estimación de la probabilidad de condena (con error según el abogado). Preparar la defensa suma con rendimientos decrecientes.',
    example: 'Abogado calidad 70 + preparación 60: defensa ≈ 70.',
    impact: 'Honorarios en cada etapa; nunca garantiza la absolución.',
  },
  { id: 'inspeccion', term: 'Inspección', category: 'Sistema legal',
    short: 'Control de las autoridades a una empresa que puede terminar en multa.',
    purpose: 'Representar controles administrativos habituales.',
    how: 'Cada mes una empresa puede ser inspeccionada (más probable sin mantenimiento). Podés pagar la multa, impugnarla con un abogado o intentar un soborno (ilegal). Si no hacés nada, se duplica.',
    example: 'Multa de $600 por cartelería faltante.',
    impact: 'Gasto de la empresa.',
  },
  { id: 'antecedentes', term: 'Antecedentes penales', category: 'Sistema legal',
    short: 'Registro de condenas previas.',
    purpose: 'Reflejar la reincidencia.',
    example: 'Con antecedentes, tus postulaciones a empleos tienen 40 % menos probabilidad de éxito y las penas son más largas.',
    impact: 'Empleo y futuras condenas.',
  },
];
