import type { GlossaryEntry } from './glossary';

type A = Omit<GlossaryEntry, 'category'>;
const act = (e: A): GlossaryEntry => ({ ...e, category: 'Acciones del juego' });

/** Versión 1.1: proyección de negocios, gestor de inversiones, capacitación y "Mis inversiones". */
export const GLOSSARY_V11: GlossaryEntry[] = [
  { id: 'proyeccion_negocios', term: 'Proyección de negocios', category: 'Empresas',
    short: 'Estimación de cómo le puede ir a un negocio en los próximos meses: ventas, ganancias, caja y probabilidad de sobrevivir.',
    purpose: 'Decidir si conviene abrir, comprar o mantener un negocio, y con cuánto capital, ANTES de arriesgar dinero.',
    how: 'El juego simula varios futuros posibles de tu negocio con las reglas reales (economía, demanda, competencia, costos) y distinto azar en cada uno. Con más nivel de la habilidad se simulan más futuros y tu lectura se desvía menos. Nunca es exacta: el futuro real puede salir fuera del rango.',
    example: 'Minimercado con $40,000: en 9 de cada 10 futuros sigue abierto al año; escenario central gana desde el mes 2; en el escenario malo la caja baja a $12,000.',
    impact: 'Te ayuda a elegir sector, capital y forma legal. Comparar la proyección con lo que pasó después te da experiencia.',
    risks: 'Con nivel bajo tu lectura tiene sesgo (optimista o pesimista) aunque la simulación sea correcta.',
    tip: 'Mirá el escenario malo: si en él la caja se vuelve negativa, poné más capital o elegí una SRL.' },
  { id: 'escenarios_bandas', term: 'Escenario malo, central y bueno', category: 'Básicos',
    short: 'Tres puntos de un rango de resultados posibles: 10 %, 50 % y 90 %.',
    purpose: 'Mostrar la incertidumbre en vez de una sola cifra engañosa.',
    how: 'Escenario malo (10 %): solo 1 de cada 10 futuros sale peor. Central (50 %): la mitad sale mejor y la mitad peor. Bueno (90 %): solo 1 de cada 10 sale mejor.',
    example: 'Ventas del mes 12: malo $18,000, central $24,000, bueno $31,000.',
    impact: 'Planificá para el malo y esperá el central.',
    mistakes: 'Tomar el escenario bueno como si fuera lo esperado.' },
  { id: 'probabilidad_supervivencia', term: 'Probabilidad de sobrevivir', category: 'Empresas',
    short: 'En cuántos de los futuros simulados la empresa sigue operando sin deudas vencidas al final.',
    purpose: 'Medir el riesgo de quiebra de un negocio nuevo.',
    example: '70 %: en 3 de cada 10 futuros la empresa termina insolvente o cerrada.',
    impact: 'Por debajo de 60 % el riesgo es alto: más capital, menos costos fijos o responsabilidad limitada.' },
  { id: 'gestor_inversiones', term: 'Gestor de inversiones', category: 'Profesionales',
    short: 'Profesional al que le das dinero para que lo invierta por vos en acciones y fondos.',
    purpose: 'Invertir sin tener que elegir cada acción vos mismo.',
    how: 'El gestor estima el valor justo de cada acción con un error que baja con su calidad y experiencia (±60 % × (1 − habilidad/110), mínimo ±6 %). Como los precios tienden a su valor justo, estimar mejor es elegir mejor. Rebalancea cada mes según tu perfil. Los buenos reducen acciones en recesión; los malos venden en el pánico y compran en la euforia. Todo pasa en el mercado real del juego.',
    example: 'Le das $20,000 con perfil moderado: invierte ~60 % en 6 acciones que considera baratas, ~30 % en el fondo de bonos y ~10 % en el fondo monetario.',
    impact: 'Tu dinero queda en "Cartera con gestor", valuada cada día. La ganancia tributa cuando retirás.',
    risks: 'Ningún gestor garantiza ganancias: si el mercado cae, tu cuenta también. Un gestor malo puede rendir menos que un fondo índice después de sus comisiones.',
    tip: 'La reputación estima la calidad con error: mirá sus resultados frente al índice durante un año antes de darle más dinero.' },
  { id: 'comision_gestion', term: 'Comisión de gestión', category: 'Bolsa e inversiones',
    short: 'Porcentaje anual del valor de tu cuenta que cobra el gestor, ganes o pierdas.',
    purpose: 'Es el costo fijo de delegar la inversión.',
    formula: 'Cada mes: valor de la cuenta × comisión anual ÷ 12.',
    example: '1.5 % anual sobre $20,000 = $25 por mes.',
    impact: 'Reduce tu rendimiento todos los años: en 10 años, 1.5 % anual se come cerca del 14 % del capital.' },
  { id: 'comision_exito', term: 'Comisión de éxito', category: 'Bolsa e inversiones',
    short: 'Parte de la ganancia que se lleva el gestor, solo por encima del máximo anterior de tu cuenta.',
    purpose: 'Premiar al gestor cuando gana dinero para vos.',
    how: 'Se calcula cada 31 de diciembre y al cerrar la cuenta. Si la cuenta cae y luego se recupera, no cobra de nuevo por recuperar lo perdido (máximo histórico).',
    formula: '(valor por unidad − máximo anterior) × unidades × comisión.',
    example: 'Tu cuenta pasa de $100 a $112 por unidad con 15 % de comisión: paga 15 % de los $12 ganados.',
    impact: 'Solo pagás si ganás, pero reduce la ganancia neta.' },
  { id: 'perfil_inversion', term: 'Perfil de inversión', category: 'Bolsa e inversiones',
    short: 'Cuánto riesgo aceptás: conservador, moderado o agresivo.',
    purpose: 'Define la mezcla entre acciones (crecen más y caen más), bonos y liquidez.',
    example: 'Conservador 25 % acciones · Moderado 60 % · Agresivo 90 %.',
    impact: 'Más acciones = más ganancia esperada a largo plazo y caídas más grandes en el camino.',
    tip: 'Si vas a necesitar el dinero pronto, elegí un perfil conservador.' },
  { id: 'capacitacion_profesional', term: 'Capacitar a un profesional', category: 'Profesionales',
    short: 'Pagarle cursos a un profesional contratado para que haga mejor su trabajo.',
    purpose: 'Mejorar su calidad real sin cambiar de profesional.',
    how: 'Sube su calidad en (100 − calidad) × 12 % (mínimo 1 punto). Se puede hacer cada 90 días y cada vez cuesta un 50 % más. Además, todos los profesionales contratados ganan un año de experiencia cada diciembre.',
    example: 'Un gestor con calidad 50 sube a 56 tras una capacitación.',
    impact: 'Gestores que eligen mejor, contadores que reclaman más deducciones, abogados con mejor defensa.' },
  { id: 'mis_inversiones', term: 'Mis inversiones', category: 'Bolsa e inversiones',
    short: 'Lista única con todo lo que tenés invertido: acciones, bonos, fondos, Mogul, cuentas con gestor e inmuebles.',
    purpose: 'Ver y operar todo desde un solo lugar.',
    how: 'Tocá cualquier inversión para ver su resultado y comprar más o vender ahí mismo.',
    example: 'Tocás NBLA → ves que ganás $320 → vendés 10 acciones sin buscarla en la bolsa.',
    impact: 'Las operaciones son las mismas que en cada sección: misma contabilidad y comisiones.' },
  act({ id: 'accion_proyectar', term: 'Proyectar el negocio', short: 'Simula varios futuros posibles del negocio y te muestra el rango de resultados.', purpose: 'Decidir con información antes de invertir.', how: 'Cuantos más futuros y menos sesgo, mejor la proyección: ambos mejoran con la habilidad Proyección de negocios. Suma XP (con rendimientos decrecientes en el mismo día).', example: 'Proyectar una cafetería con $30,000 antes de fundarla.', impact: 'No cambia tu partida real. Si fundás o comprás, la proyección se guarda para compararla después.' }),
  act({ id: 'accion_gestor_aportar', term: 'Darle dinero al gestor', short: 'Transfiere dinero de tu cuenta corriente a la cuenta que administra el gestor.', purpose: 'Que lo invierta por vos.', how: 'Recibís unidades al valor del día; el gestor invierte el dinero en el próximo día hábil.', example: 'Aportás $5,000 con valor por unidad $104 → recibís 48.08 unidades.', impact: 'Baja tu liquidez; sube "Cartera con gestor".', risks: 'El valor de la cuenta puede bajar.' }),
  act({ id: 'accion_gestor_retirar', term: 'Retirar del gestor', short: 'El gestor vende a prorrata y te devuelve el dinero.', purpose: 'Recuperar liquidez o cambiar de gestor.', how: 'Pagás el costo de vender (diferencial y comisión). Si retirás todo, se cobra la comisión de éxito pendiente y la cuenta se cierra. La ganancia frente a lo que aportaste tributa como ganancia de capital.', example: 'Retirás $3,000 de una cuenta de $10,000: vende 30 % de cada posición.', impact: 'Entra dinero a la cuenta corriente.' }),
  act({ id: 'accion_gestor_perfil', term: 'Cambiar el perfil', short: 'Le indica al gestor cuánto riesgo tomar.', purpose: 'Adaptar la cuenta a tus planes.', example: 'Pasar de agresivo a conservador antes de necesitar el dinero.', impact: 'El gestor rebalancea en el próximo día hábil (con costos de compraventa).' }),
  act({ id: 'accion_capacitar_pro', term: 'Capacitar', short: 'Pagás una capacitación al profesional contratado.', purpose: 'Que trabaje mejor.', how: 'Sube su calidad real con rendimientos decrecientes. Una vez cada 90 días; cada vez cuesta 50 % más.', example: 'Capacitar a tu gestor antes de darle más dinero.', impact: 'Gasto profesional hoy; mejores decisiones del profesional en adelante.' }),
  act({ id: 'accion_operar_rapido', term: 'Operar desde Mis inversiones', short: 'Comprar más o vender una inversión que ya tenés, sin buscarla.', purpose: 'Ahorrar pasos.', example: 'Vender la mitad de tus participaciones de un fondo desde la lista.', impact: 'Usa exactamente las mismas reglas, precios y comisiones que la sección de origen.' }),
];
