import type { GlossaryEntry } from './glossary';

type A = Omit<GlossaryEntry, 'category'>;
const act = (e: A): GlossaryEntry => ({ ...e, category: 'Acciones del juego' });

/** Versión 1.2: tiendas e imagen, niveles de tarjeta y cuotas, noticias y rivales, misiones y actualizaciones. */
export const GLOSSARY_V12: GlossaryEntry[] = [
  // ---------------------------------------------------------------- Estilo de vida
  { id: 'imagen_personal', term: 'Imagen personal', category: 'Estilo de vida',
    short: 'Puntaje de 0 a 100 que resume cómo te presentás: ropa que llevás puesta, reloj y accesorios, vehículo y reputación.',
    purpose: 'Cambia cómo te tratan: en entrevistas, al negociar un sueldo y en las tiendas.',
    how: 'Ropa puesta (hasta 50 puntos), reloj y accesorio (hasta 22), tu mejor vehículo (hasta 20) y reputación (hasta 8). La ropa gastada (estado menor a 40 %) rinde la mitad.',
    example: 'Remera, jean y zapatillas gastadas ≈ 6 puntos. Camisa, chino, zapatos y saco de Urbana Moda ≈ 26. Con traje de sastre y un reloj clásico ≈ 46.',
    impact: 'Postulaciones: ±6 puntos de probabilidad según lo que se espera para el nivel del puesto (nivel 1: 5; nivel 5: 50). Negociar sueldo: ±3 puntos. Tiendas: con más imagen te atienden mejor y te hacen descuento. También suma a tu reputación (hasta +10).',
    risks: 'Gastar en imagen más de lo que te devuelve. La ropa se gasta y hay que reponerla; los autos se deprecian.',
    tip: 'Para un primer empleo alcanza con ropa correcta. Para puestos gerenciales, invertí en imagen antes de postularte.' },
  { id: 'trato_tiendas', term: 'Trato en las tiendas', category: 'Estilo de vida',
    short: 'Cómo te atienden según tu imagen: con desgano, normal o como cliente preferente.',
    purpose: 'Las tiendas de mayor categoría esperan clientes bien presentados.',
    how: 'Cada categoría pide una imagen mínima: popular 0, media 10, premium 25, lujo 45. Con 20 puntos por encima sos cliente preferente (3 % a 10 % de descuento). Debajo del mínimo no te muestran la colección exclusiva. Las tarjetas Oro, Platino y Black suman reconocimiento (+3, +8, +15).',
    example: 'Con imagen 30 en una tienda premium (mínimo 25) te atienden bien; con 45 o más te descuentan 7 %.',
    impact: 'Más descuento y acceso a artículos que suman mucha imagen.' },
  { id: 'bienes_personales', term: 'Bienes personales', category: 'Estilo de vida',
    short: 'Vehículos, tecnología, muebles y joyas: cosas que compraste y todavía valen dinero.',
    purpose: 'Aparecen en tu balance como activo, a diferencia de la ropa (que es consumo).',
    how: 'Se registran al precio de compra y pierden valor cada mes (depreciación). Al venderlos te pagan una parte de su valor actual (por ejemplo, 85 % en un auto, 50 % en un celular).',
    formula: 'Depreciación mensual = valor actual × tasa anual ÷ 12 (nunca por debajo del 5 % del precio).',
    example: 'Un sedán de $24.000 con 15 % anual pierde $300 el primer mes. Venderlo el mismo día te daría $21.120 (88 %).',
    impact: 'Suman a tu patrimonio, pero la depreciación es un gasto real (no sale dinero cada mes, pero tu patrimonio baja).',
    mistakes: 'Pensar que un auto 0 km es una inversión: salvo relojes y joyas, casi todo pierde valor.' },
  { id: 'vehiculo', term: 'Vehículo propio', category: 'Estilo de vida',
    short: 'Bicicleta, moto o auto: reemplaza el transporte de tu estilo de vida por sus costos propios.',
    purpose: 'Más imagen, menos estrés y, a veces, menos gasto en transporte.',
    how: 'Con un vehículo, el gasto de "Transporte" del presupuesto pasa a ser combustible, seguro y mantenimiento del vehículo (la bicicleta cubre la mitad de los viajes). Solo cuenta tu mejor vehículo.',
    example: 'Estilo modesto: transporte $60. Con un auto usado pasás a pagar ~$210 por mes, pero sumás 6 de imagen y bajás el estrés.',
    impact: 'Cambia tus gastos fijos mensuales y tu imagen. Se deprecia cada mes.' },
  { id: 'tecnologia_hogar', term: 'Tecnología y hogar', category: 'Estilo de vida',
    short: 'Artículos con efectos concretos: estudiar mejor, más red de contactos, más salud, menos estrés o menos gasto en comida.',
    purpose: 'Invertir en tu productividad y bienestar.',
    how: 'Notebook: +10 % de aprendizaje en cursos; notebook profesional +18 %; tablet +5 %; escritorio +6 % (cuenta el mejor). Celulares: suman red de contactos cada mes. Cocina equipada: −12 % en comida. Colchón, sillón y gimnasio: salud y estrés.',
    example: 'Una cocina de $2.400 con comida de $250 por mes te ahorra $30 por mes: se paga en unos 7 años (además se deprecia).',
    impact: 'Los efectos se aplican cada mes mientras tengas el artículo.' },
  { id: 'apariencia', term: 'Apariencia del personaje', category: 'Estilo de vida',
    short: 'Tono de piel, peinado y color de pelo de tu personaje.',
    purpose: 'Personalizar cómo se ve. No cambia ningún número: la imagen depende de la ropa, no de tu físico.',
    example: 'Elegís pelo corto castaño: el dibujo del personaje se actualiza al instante.',
    impact: 'Solo visual.' },
  // ---------------------------------------------------------------- Tarjetas
  { id: 'nivel_tarjeta', term: 'Nivel de tarjeta (Clásica, Oro, Platino, Black)', category: 'Crédito y deuda',
    short: 'Tarjetas de mayor nivel dan más límite y beneficios, a cambio de un costo anual y requisitos más altos.',
    purpose: 'Que la tarjeta rinda: reintegros, cuotas sin interés y mejor trato.',
    how: 'Oro: puntaje 680, ingresos $2.500/mes (o patrimonio $40.000), 6 meses de historial; 1 % de reintegro; costo $95/año. Platino: 730, $6.000 (o $150.000), 12 meses; 1,5 %; $395. Black: 780, $20.000 (o $1.000.000), 24 meses; 2 %; $1.200. Pedir una tarjeta superior es una consulta a tu crédito y puede rechazarse aun cumpliendo (más probable cerca del mínimo).',
    example: 'Gastás $1.500 por mes con tarjeta Oro y pagás el resumen completo: recibís $15 por mes, $180 por año, y pagás $95 de costo anual.',
    impact: 'El reintegro solo conviene si pagás el resumen completo: los intereses de financiar un saldo son mucho mayores.',
    risks: 'El costo anual se cobra aunque no uses la tarjeta.' },
  { id: 'reintegro_tarjeta', term: 'Reintegro (cashback)', category: 'Crédito y deuda',
    short: 'Porcentaje de lo que pagás con la tarjeta que el banco te devuelve.',
    purpose: 'Premiar el uso de la tarjeta.',
    how: 'Se acumula con cada consumo (compras, gastos del presupuesto pagados con tarjeta, cuotas) y se acredita en el resumen del día 25: descuenta tu saldo o, si no hay saldo, entra a tu cuenta.',
    example: 'Tarjeta Platino (1,5 %): pagás $2.000 de gastos del mes con ella → $30 de reintegro.',
    impact: 'Es un ingreso en tu estado de resultados.' },
  { id: 'cuotas_tarjeta', term: 'Compra en cuotas', category: 'Crédito y deuda',
    short: 'Pagar una compra en 3, 6 o 12 partes mensuales que llegan en cada resumen.',
    purpose: 'Comprar algo grande sin pagarlo todo junto.',
    how: 'El total ocupa tu límite desde el primer día y queda como "Cuotas de tarjeta a vencer". Cada resumen pasa una cuota al saldo. Son sin interés si la tienda lo ofrece y tu tarjeta lo permite (Oro 3, Platino 6, Black 12); si no, llevan la tasa de la tarjeta.',
    formula: 'Cuota con interés = monto × i ÷ (1 − (1 + i)^−n), con i = tasa anual × 0,9 ÷ 12.',
    example: 'Notebook de $900 en 6 cuotas sin interés = $150 por mes.',
    impact: 'Si no pagás el resumen completo, la cuota que entró genera intereses como cualquier saldo.',
    mistakes: 'Acumular cuotas de muchas compras: comprometen tus ingresos de los próximos meses.' },
  // ---------------------------------------------------------------- Noticias y competencia
  { id: 'noticias_rumores', term: 'Noticias y rumores', category: 'Mercado y competencia',
    short: 'Anticipos de lo que puede pasar: eventos económicos, resultados de empresas, compras de rivales, exclusividades con proveedores.',
    purpose: 'Darte ventaja si analizás bien: podés comprar, vender o prepararte antes de que ocurra.',
    how: 'Cada noticia tiene una probabilidad real de ser cierta que no ves. Ves la confiabilidad típica de la fuente (rumores ~50 %, analistas ~70 %, prensa ~85 %). En el juego la calibración es exacta: de las noticias con 70 % de confiabilidad, 7 de cada 10 se cumplen.',
    example: 'Rumor: "Se anticipa un shock del petróleo". Si lo creés, podés comprar acciones de energía antes; si era falso, perdés la oportunidad de otras inversiones.',
    impact: 'Los hechos confirmados se marcan como "Cumplida" o "Desmentida" para que aprendas qué fuentes creer.',
    risks: 'Ningún análisis da certeza: incluso con nivel máximo te podés equivocar.' },
  { id: 'confiabilidad_fuente', term: 'Confiabilidad de una noticia', category: 'Mercado y competencia',
    short: 'Probabilidad de que una noticia sea cierta.',
    purpose: 'Decidir cuánto arriesgar según una noticia.',
    how: 'Sin analizar, solo sabés el promedio de la fuente. Al analizar, estimás la de ESA noticia con un error de ±30 % (nivel 1) a ±3 % (nivel 100) según tu habilidad: Educación financiera para economía, Predicción bursátil para bolsa, Administración para empresas y proveedores, Bienes raíces para inmuebles.',
    example: 'Un rumor típico de 50 %: tu análisis con nivel 40 estima 78 % (error típico ±19 %).',
    impact: 'Mejores estimaciones = mejores decisiones con el tiempo.' },
  { id: 'grupos_rivales', term: 'Grupos rivales', category: 'Mercado y competencia',
    short: 'Cuatro grupos económicos controlados por la IA que compiten con vos.',
    purpose: 'Que el mercado tenga vida: otros compran, abren negocios y te disputan empleados y proveedores.',
    how: 'Cada mes pueden comprar empresas o inmuebles en venta (antes que vos), abrir un competidor en tu sector, cerrar exclusividades con proveedores, ofertar por tus empresas rentables y ofrecer más sueldo a tus mejores empleados. Casi todo se anticipa con rumores.',
    example: 'Rumor: "Grupo Altamira negocia comprar Café Central". Si lo querías, comprarlo ya evita perderlo.',
    impact: 'Más competencia baja tus ventas; sus ofertas te permiten vender caro.' },
  { id: 'exclusividad_proveedor', term: 'Exclusividad con un proveedor', category: 'Mercado y competencia',
    short: 'Un rival acuerda prioridad con un proveedor y este sube sus precios al resto por varios meses.',
    purpose: 'Es una forma real de competencia por insumos.',
    how: 'El precio de ese proveedor sube entre 15 % y 35 % durante 3 a 6 meses. Tu pedido y el cálculo de inventario lo muestran.',
    example: 'Mayorista El Puerto +22 %: te conviene pasar a otro proveedor o haber comprado stock antes (si no vence).',
    impact: 'Sube tu costo de ventas y baja tu margen.' },
  { id: 'caza_talentos', term: 'Oferta a tus empleados', category: 'Mercado y competencia',
    short: 'Un rival le ofrece más sueldo a uno de tus mejores empleados.',
    purpose: 'Competencia por talento.',
    how: 'Tenés 10 días para igualar la oferta (sube su sueldo y su moral) o dejarlo ir. Si no respondés y la oferta supera su sueldo en más de 15 %, se va; si no, se queda con menos moral.',
    example: 'Te ofrecen quedarte con tu cocinera de habilidad 80 igualando $1.300: perderla bajaría calidad y ventas.',
    impact: 'Igualar sube tu nómina; perderlo baja tu capacidad o calidad hasta reemplazarlo.' },
  { id: 'oferta_rival', term: 'Oferta de compra de un rival', category: 'Mercado y competencia',
    short: 'Un grupo rival ofrece comprarte una empresa rentable.',
    purpose: 'Vender a buen precio sin buscar comprador.',
    how: 'Llega a empresas con ganancias en los últimos 3 meses. Los grupos agresivos suelen pagar por encima de la valoración; los oportunistas, por debajo. Vale 15 días.',
    example: 'Grupo Altamira ofrece $180.000 por tu cafetería valorada en $150.000 (+20 %).',
    impact: 'Si aceptás, cobrás y la empresa deja de ser tuya (la ganancia de capital tributa).' },
  // ---------------------------------------------------------------- Inmuebles de entrada
  { id: 'cochera', term: 'Cochera', category: 'Bienes raíces',
    short: 'Espacio de estacionamiento: el inmueble más barato para empezar a cobrar alquileres.',
    purpose: 'Entrar al mercado inmobiliario con poco capital.',
    how: 'De 11 a 15 m², poco mantenimiento e inquilinos más cumplidores que en viviendas. No se puede usar como vivienda ni como local.',
    example: 'Cochera en Zona Sur a $6.000 alquilada a $40 por mes: 8 % bruto anual.',
    impact: 'Renta chica pero estable; paga impuesto inmobiliario.' },
  { id: 'estudio_inmueble', term: 'Estudio o monoambiente', category: 'Bienes raíces',
    short: 'Vivienda chica (18 a 34 m²): la opción de entrada para alquilar o para vivir.',
    purpose: 'Comprar tu primera vivienda o empezar a invertir sin cientos de miles.',
    example: 'Estudio de 24 m² en Zona Sur a $22.000 alquilado a $150 por mes: 8 % bruto.',
    impact: 'Si vivís en él, dejás de pagar alquiler.' },
  // ---------------------------------------------------------------- Guía y app
  { id: 'misiones', term: 'Misiones', category: 'Básicos',
    short: 'Objetivos cortos que te enseñan cada sistema del juego ("Comprá tu primera acción", "Cobrá tu primer alquiler").',
    purpose: 'Aprender de a poco sin abrumarte.',
    how: 'Se cumplen solas cuando lo hacés de verdad y te dan experiencia en la habilidad relacionada. Están ordenadas por capítulos según tu etapa, pero podés hacerlas en cualquier orden.',
    example: 'Cumplís "Cobrá tu primer alquiler" → +250 XP en Bienes raíces.',
    impact: 'Nunca bloquean nada.' },
  { id: 'secciones_recomendadas', term: 'Secciones recomendadas por etapa', category: 'Básicos',
    short: 'Algunas secciones avanzadas muestran un aviso si entrás antes de la etapa recomendada.',
    purpose: 'Que un jugador nuevo no se abrume ni arriesgue dinero que necesita.',
    how: 'El aviso explica por qué conviene esperar y qué hacer antes. Tocando "Abrir igual" entrás y no se vuelve a mostrar. En Ajustes podés mostrar todo desde el inicio.',
    example: 'En etapa 1, Negocios te sugiere tener primero un ingreso estable y un fondo de emergencia.',
    impact: 'Ninguna sección está bloqueada.' },
  { id: 'actualizaciones', term: 'Actualizaciones', category: 'Básicos',
    short: 'La app descarga versiones nuevas del juego por internet sin reinstalar la APK y sin tocar tu partida.',
    purpose: 'Mejoras y correcciones sin perder el progreso.',
    how: 'Verifica tamaño y huella SHA-256 del archivo, guarda tu partida y una copia previa, abre la versión nueva y solo la deja fija si funciona. Si falla, vuelve sola a la anterior. Algunos cambios (permisos, ícono) requieren instalar una APK nueva: se instala encima de la anterior y conserva la partida.',
    example: 'Aparece "Versión 1.2.1 disponible" → Actualizar → en unos segundos se reinicia con la versión nueva.',
    impact: 'Tu partida vive en los archivos privados de la app: la actualización no la borra.',
    tip: 'Exportá una copia a un archivo de vez en cuando (Ajustes → Guardado): es tu seguro ante cualquier imprevisto.' },
  // ---------------------------------------------------------------- Acciones
  act({ id: 'accion_comprar_tienda', term: 'Comprar en una tienda', short: 'Elegís cómo pagar: débito, efectivo, tarjeta en un pago o en cuotas.', purpose: 'Comprar ropa, vehículos, tecnología, hogar o lujo.', how: 'Débito y efectivo no generan deuda. Con tarjeta sumás reintegro según tu nivel. En cuotas, el total ocupa tu límite y cada mes llega una cuota al resumen.', example: 'Camisa de $45 con tarjeta Oro: $0,45 de reintegro en el próximo resumen.', impact: 'La ropa es gasto; lo demás queda como bien personal (activo que se deprecia).', risks: 'Comprar en cuotas lo que no podrías pagar de contado.' }),
  act({ id: 'accion_vender_bien', term: 'Vender o donar', short: 'Vendés un bien durable por una parte de su valor actual, o donás ropa.', purpose: 'Recuperar dinero o liberar espacio.', example: 'Vendés un auto valuado en $6.000 (85 %) → cobrás $5.100 y registrás $900 de pérdida.', impact: 'Entra dinero a tu cuenta corriente; la diferencia con el valor contable es pérdida o ganancia.' }),
  act({ id: 'accion_vestirse', term: 'Ponerse una prenda', short: 'Cambia lo que tenés puesto en ese lugar del cuerpo.', purpose: 'Mejorar tu imagen al instante.', example: 'Te ponés el saco de traje: tu imagen sube 11 puntos.', impact: 'Solo la ropa puesta cuenta para tu imagen; la puesta se gasta más rápido.' }),
  act({ id: 'accion_pedir_tarjeta', term: 'Pedir otra tarjeta', short: 'Solicitás un nivel superior (o bajás a uno más barato).', purpose: 'Más límite y beneficios, o menos costo anual.', how: 'Subir: consulta a tu crédito (baja un poco el puntaje por unos meses) y evaluación. Una solicitud cada 30 días. Bajar: inmediato.', example: 'Pedís Oro con puntaje 700 (mínimo 680): aprobación estimada ~88 %.', impact: 'Si te aprueban, se cobra el costo anual y cambia tu límite.' }),
  act({ id: 'accion_analizar_noticia', term: 'Analizar una noticia', short: 'Estimás qué tan probable es que sea cierta y a veces encontrás una pista.', purpose: 'Decidir con más información.', how: 'El error de la estimación baja con tu habilidad. Las pistas aciertan del 60 % al 93 % de las veces. Podés reanalizar si tu habilidad sube 10 niveles.', example: 'Analizás un rumor de bolsa con Predicción nivel 30: "estimás ~64 %; encontraste datos que la respaldan".', impact: 'Da experiencia en la habilidad del tema.' }),
  act({ id: 'accion_igualar_oferta', term: 'Igualar la oferta', short: 'Subís el sueldo del empleado al que le ofreció el rival.', purpose: 'Retener talento.', example: 'Igualás $1.300: tu nómina sube $300 por mes y el empleado gana moral.', impact: 'Más costo fijo; conservás calidad y capacidad.' }),
  act({ id: 'accion_dejar_ir', term: 'Dejarlo ir', short: 'El empleado acepta la oferta del rival y se va.', purpose: 'No pagar más de lo que vale para tu negocio.', example: 'Dejás ir a un repositor fácil de reemplazar y contratás otro.', impact: 'Baja tu nómina y, hasta reemplazarlo, tu capacidad.' }),
  act({ id: 'accion_buscar_actualizacion', term: 'Buscar actualización', short: 'Consulta si hay una versión nueva del juego.', purpose: 'Recibir mejoras sin reinstalar.', example: 'Aparece la 1.2.1 con novedades: la instalás en segundos.', impact: 'Tu partida se guarda y se conserva.' }),
  act({ id: 'accion_abrir_igual', term: 'Abrir igual', short: 'Entrás a una sección avanzada aunque todavía no tengas la etapa recomendada.', purpose: 'Libertad total para jugar como quieras.', example: 'Abrís Negocios en la etapa 1 para fundar una consultora con tu herencia.', impact: 'El aviso no vuelve a aparecer para esa sección.' }),
];
